import { useState, useEffect } from 'react';
import type { FormEvent } from 'react';
import { X, Info } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useWorkspace } from '../contexts/WorkspaceContext';
import type { Vehicle, ExpenseCategory, Driver, ExpenseRecord } from '../types';

interface AddExpenseModalProps {
    open: boolean;
    onClose: () => void;
    onSuccess: () => void;
    vehicles: Vehicle[];
    drivers?: Driver[];
    initialData?: ExpenseRecord;
}

// service, tyre, and licensing are auto-generated by database triggers
const CATEGORIES: { value: ExpenseCategory; label: string }[] = [
    { value: 'fuel', label: 'Fuel' },
    { value: 'salary', label: 'Driver Salary' },
    { value: 'insurance', label: 'Insurance' },
    { value: 'repairs', label: 'Repairs' },
    { value: 'wash', label: 'Car Wash' },
    { value: 'other', label: 'Other' },
];

const FUEL_STATIONS = [
    'Total', 'Puma', 'Engen', 'Kobil', 'Zen', 'Moil', 'Oil Libya', 'Other',
];

const INPUT_STYLE = {
    background: 'var(--ff-navy)',
    color: 'var(--ff-text-primary)',
    border: '1px solid var(--ff-border)',
    borderRadius: 8,
    padding: '8px 12px',
    fontSize: 14,
    width: '100%',
    outline: 'none',
    boxSizing: 'border-box',
} as const;

const LABEL_STYLE = {
    display: 'block',
    fontSize: 12,
    color: 'var(--ff-text-muted)',
    marginBottom: 4,
} as const;

export function AddExpenseModal({ open, onClose, onSuccess, vehicles, drivers = [], initialData }: AddExpenseModalProps) {
    const { activeWorkspaceId } = useWorkspace();
    const isEdit = !!initialData;
    // Auto-generated expenses can only be changed via their source record
    const isAutoGenerated = isEdit && !!initialData?.metadata?.source_table;

    const [form, setForm] = useState({
        vehicle_id: '',
        date: new Date().toISOString().slice(0, 10),
        amount_zmw: '',
        category: 'fuel' as ExpenseCategory,
        description: '',
        descriptionOther: '',
        driver_id: '',
        notes: '',
    });
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (!open) return;
        if (initialData) {
            const knownStation = FUEL_STATIONS.includes(initialData.description ?? '') ? (initialData.description ?? '') : 'Other';
            const isFuelCat = initialData.metadata?.category === 'fuel';
            setForm({
                vehicle_id: initialData.reference_entity_id ?? '',
                date: initialData.date,
                amount_zmw: String(initialData.amount_zmw),
                category: initialData.metadata?.category ?? 'fuel',
                description: isFuelCat ? knownStation : (initialData.description ?? ''),
                descriptionOther: isFuelCat && knownStation === 'Other' ? (initialData.description ?? '') : '',
                driver_id: initialData.metadata?.driver_id ?? '',
                notes: initialData.metadata?.notes ?? '',
            });
        } else {
            setForm({
                vehicle_id: vehicles[0]?.id ?? '',
                date: new Date().toISOString().slice(0, 10),
                amount_zmw: '',
                category: 'fuel',
                description: '',
                descriptionOther: '',
                driver_id: '',
                notes: '',
            });
        }
        setError(null);
    }, [open, initialData, vehicles]);

    useEffect(() => {
        const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
        window.addEventListener('keydown', handler);
        return () => window.removeEventListener('keydown', handler);
    }, [onClose]);

    if (!open) return null;

    const set = (field: keyof typeof form) =>
        (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) =>
            setForm(prev => ({ ...prev, [field]: e.target.value }));

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        if (isAutoGenerated) return; // should never reach, but safeguard
        setError(null);

        const resolvedDesc = form.category === 'fuel' && form.description === 'Other'
            ? form.descriptionOther.trim()
            : form.description.trim();

        if (!form.vehicle_id) { setError('Please select a vehicle.'); return; }
        const amount = Number(form.amount_zmw);
        if (!form.amount_zmw || isNaN(amount) || amount <= 0 || amount > 999999.99 || !/^\d+(\.\d{1,2})?$/.test(form.amount_zmw)) {
            setError('Enter a valid amount (0.01 – 999,999.99, max 2 decimal places).'); return;
        }

        setSubmitting(true);
        const payload = {
            workspace_id: activeWorkspaceId,
            app_id: 'transport',
            type: 'expense',
            reference_entity_id: form.vehicle_id,
            date: form.date,
            amount_zmw: Number(form.amount_zmw),
            description: resolvedDesc || null,
            metadata: {
                category: form.category,
                driver_id: form.category === 'salary' ? (form.driver_id || null) : null,
                notes: form.notes.trim() || null,
            }
        };

        const { error: supaErr } = isEdit
            ? await supabase.from('transactions').update(payload).eq('id', initialData!.id)
            : await supabase.from('transactions').insert(payload);
        setSubmitting(false);

        if (supaErr) { setError(supaErr.message); }
        else { onSuccess(); onClose(); }
    };

    const isFuel = form.category === 'fuel';

    return (
        <div onClick={onClose} style={{
            position: 'fixed', inset: 0, zIndex: 50,
            background: 'rgba(0,0,0,0.6)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: 16,
        }}>
            <div onClick={e => e.stopPropagation()} style={{
                background: 'var(--ff-surface)',
                border: '1px solid var(--ff-border)',
                borderRadius: 16, width: '100%', maxWidth: 460, padding: 28,
                boxShadow: '0 24px 60px rgba(0,0,0,0.5)',
                maxHeight: '90vh', overflowY: 'auto',
            }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
                    <h2 style={{ fontSize: 18, fontWeight: 700, color: 'var(--ff-text-primary)' }}>
                        {isEdit ? 'Edit Expense' : 'Add Expense'}
                    </h2>
                    <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--ff-text-muted)', padding: 4 }}>
                        <X size={20} />
                    </button>
                </div>

                {/* Auto-generated read-only notice */}
                {isAutoGenerated && (
                    <div style={{ marginBottom: 16, padding: '12px 14px', borderRadius: 8, background: '#3b82f615', border: '1px solid #3b82f640', fontSize: 13, color: '#3b82f6', display: 'flex', gap: 8 }}>
                        <Info size={16} style={{ flexShrink: 0, marginTop: 1 }} />
                        This expense was auto-generated from a {initialData?.metadata?.source_table?.replace(/_/g, ' ')} record.
                        To change it, edit the original {initialData?.metadata?.source_table?.replace(/_/g, ' ')} entry.
                    </div>
                )}

                {error && (
                    <div style={{ marginBottom: 16, padding: '10px 14px', borderRadius: 8, background: '#ef444420', color: '#ef4444', border: '1px solid #ef444440', fontSize: 13 }}>
                        {error}
                    </div>
                )}

                <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 14, opacity: isAutoGenerated ? 0.5 : 1, pointerEvents: isAutoGenerated ? 'none' : undefined }}>
                    <div>
                        <label style={LABEL_STYLE}>Vehicle *</label>
                        <select style={INPUT_STYLE} value={form.vehicle_id} onChange={set('vehicle_id')}>
                            {vehicles.length === 0
                                ? <option value="">No vehicles registered yet</option>
                                : vehicles.map(v => <option key={v.id} value={v.id}>{v.plate} — {v.make} {v.model}</option>)}
                        </select>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                        <div>
                            <label style={LABEL_STYLE}>Date *</label>
                            <input type="date" style={INPUT_STYLE} value={form.date} onChange={set('date')} />
                        </div>
                        <div>
                            <label style={LABEL_STYLE}>Category *</label>
                            <select style={INPUT_STYLE} value={form.category} onChange={set('category')}>
                                {CATEGORIES.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}
                            </select>
                        </div>
                    </div>

                    <div>
                        <label style={LABEL_STYLE}>{isFuel ? 'Fuel Station' : 'Description'}</label>
                        {isFuel ? (
                            <>
                                <select style={INPUT_STYLE} value={form.description} onChange={set('description')}>
                                    <option value="">— Select station —</option>
                                    {FUEL_STATIONS.map(s => <option key={s} value={s}>{s}</option>)}
                                </select>
                                {form.description === 'Other' && (
                                    <input style={{ ...INPUT_STYLE, marginTop: 8 }} placeholder="Enter station name"
                                        value={form.descriptionOther} onChange={set('descriptionOther')} />
                                )}
                            </>
                        ) : (
                            <input style={INPUT_STYLE} placeholder="Optional description"
                                value={form.description} onChange={set('description')} />
                        )}
                    </div>

                    {form.category === 'salary' && drivers.length > 0 && (
                        <div>
                            <label style={LABEL_STYLE}>Driver Being Paid</label>
                            <select style={INPUT_STYLE} value={form.driver_id} onChange={set('driver_id')}>
                                <option value="">— Select driver —</option>
                                {drivers.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
                            </select>
                        </div>
                    )}

                    <div>
                        <label style={LABEL_STYLE}>Amount (ZMW) *</label>
                        <input type="number" min="0.01" step="0.01" style={INPUT_STYLE} placeholder="0.00"
                            value={form.amount_zmw} onChange={set('amount_zmw')} autoFocus />
                    </div>

                    <div>
                        <label style={LABEL_STYLE}>Notes</label>
                        <textarea rows={2} style={{ ...INPUT_STYLE, resize: 'vertical' } as React.CSSProperties}
                            placeholder="Any additional notes…" value={form.notes} onChange={set('notes')} />
                    </div>

                    <div style={{ display: 'flex', gap: 10, marginTop: 4 }}>
                        <button type="button" onClick={onClose} style={{
                            flex: 1, padding: '10px 0', borderRadius: 8, fontSize: 14,
                            background: 'var(--ff-navy)', color: 'var(--ff-text-muted)',
                            border: '1px solid var(--ff-border)', pointerEvents: 'auto',
                        }}>Cancel</button>
                        {!isAutoGenerated && (
                            <button type="submit" disabled={submitting} style={{
                                flex: 1, padding: '10px 0', borderRadius: 8, fontSize: 14,
                                fontWeight: 600, background: submitting ? '#334155' : '#ef4444',
                                color: 'white', border: 'none',
                            }}>{submitting ? 'Saving…' : isEdit ? 'Save Changes' : 'Add Expense'}</button>
                        )}
                    </div>
                </form>
            </div>
        </div>
    );
}
